### ISSUE TITLE
Require click-accept of terms of membership to join

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#12]
https://docs.google.com/document/d/1_XVSvZxCW2IxUYv3y1y8LWymB1PskBr8fK3tLIrdyfw/edit

**Comment by billyc** [comment]
I've created the form and it looks good but the actual enforcement will have to wait until morning.

**Comment by billyc** [comment]
oops, works locally but failed when pushed live. grrr. investigating.

**Comment by billyc** [comment]
seems to be working now. :-)
