### ISSUE TITLE
Add origin story

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#2]

**Comment by DavidOry** [comment]
For your consideration and with apologies for the delay:

At the 2015 Transportation Research Board (TRB) Annual Meeting, a scientist from the National Oceanic and Atmospheric Administration's [Hurricane Forecast Improvement Program](http://www.hfip.org/) gave an inspiring presentation to the [TRB Standing Committee on Transportation Demand Forecasting (ADB40)](http://www.trb.org/ADB40/ADB40.aspx).  The presentation motivated a lot of thinking about how the travel modeling community could more systematically improve our forecasting efforts. 

At the 2016 TRB Annual Meeting, a session entitled _From Ad Hoc to Scientific: Moderated Discussion on Improving Travel Forecasting Methods_ ([session 547](https://annualmeeting.mytrb.org/InteractiveProgram/Details/3037)) engaged the travel modeling community in a discussion about explicitly improving the empirical basis for improving our methods.  Then at the 2016 TRB Innovations in Travel Modeling Conference a session called _Getting Down to the Business of Advancing the Practice of Travel Modeling_ ([session 6C](http://onlinepubs.trb.org/onlinepubs/conferences/2016/ITM/Program.pdf)) discussed what the Mission and Vision of a hypothetical foundation focused on improving travel modeling practice could be.  Following the session, a working group of TRB Standing Committee ADB40 members and friends put together a [version 1.0 mission/vision/goals/principles statement](https://github.com/MetropolitanTransportationCommission/travel-modeling-as-science/wiki/Mission,-Vision,-Goals,-Principles) for what we are now calling _The Zephyr Foundation for Advancing Travel Analysis Methods_. The working group -- henceforth referred to as "the instigators" -- members are Billy Charlton, Greg Erhardt, Brian Gardner, David Ory, Elizabeth Sall, and Joan Walker.    

The instigators are now actively working on standing up the Zephyr Foundation.
