### ISSUE TITLE
fix top margin for simple.html layout

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#24]
Right now text is bleeding under the nav bar

**Comment by billyc** [comment]
@e-lo  browser? screen size?  Attach screen shot plz?  I believe you but I'm not seeing that here.

**Comment by e-lo** [comment]
Chrome; [privacy policy pages](http://zephyrtransport.org/privacy-policy/) as an example but happens for all pages for me
![image](https://user-images.githubusercontent.com/794787/34581173-64833938-f144-11e7-9b1a-f5b027da35ea.png)
