### ISSUE TITLE
resolve conflicting terms-of-membership and membership-terms

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#27]
@billyc and @e_lo both added.
 - I like using the name terms-of-membership b/c it is the legal noun but am fine with B's page content
- Note that logo is going to be added to top-left corner anyway, so not sure we need it again in any of the page subtitles

**Comment by e-lo** [comment]
assigning to b since he is using it as link

**Comment by billyc** [comment]
Oh LOL, I have no opinion on this whatsoever!! Will happily change all of my references to "terms of membership" including the link.

**Comment by billyc** [comment]
changed refs to terms-of-membership.
