### ISSUE TITLE
Something funny is up with the CSS or the Divs...

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#29]
![image](https://user-images.githubusercontent.com/794787/34633227-b31405e6-f22f-11e7-8824-39dbe36aefdf.png)

Strange whitespace to left of header photo. Strange spacing below.

**Comment by e-lo** [comment]
...and didn't mean for that photo to be fullsize.whoops

**Comment by billyc** [comment]
fixed. oops
