### ISSUE TITLE
add DNS to surge so people don't think they are getting scammed

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#38]

**Comment by e-lo** [comment]
does that mean buying an SSL certificate?

**Comment by billyc** [comment]
It requires an SSL cert, yes. Working on DNS changes & SSL now... stay tuned

**Comment by billyc** [comment]
I experimented with free LetsEncrypt cert on Surge, they did not play nicely together. I had to make a test change to DNS, which borked things, and it's now switched back (but the revert will take a few minutes to propagate).

What this means:  
- Current site still has the redirect to the surge membership page 
- We can purchase an SSL cert from anyone (rapidSSL has $99 / 2years)
- once we have that set up, we can move to a fully https: domain

**Comment by billyc** [comment]
@e-lo Looks like Surge is working now, maybe it just took a while to propagate. I switched the DNS over. Lemme know if it's not working for you.

**Comment by e-lo** [comment]
Working now (looks like)
