### ISSUE TITLE
Events: show events that are happening today

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#57]
Right now it only shows upcoming (date>today) but we want to show events that are happening today!

**Comment by billyc** [comment]
this is fixed, but note that the date calculations are based on when the site is BUILT, not when the site is being VIEWED.   So slightly stale events will remain on the front page after the date has past, at least until the site is next rebuilt.

I think this is fine actually -- a recent event stays on the front page for a bit.

**Comment by e-lo** [comment]
We usually post updates right after the event, so that is fine.
