### ISSUE TITLE
Update Open Science webpage for 2023

### ISSUE THREAD

**Issue by lmz** [ZephyrTransport/zephyr-website#67]
Will assign to @jfhawkin once I'm able to add him to the organization
Page to update: https://github.com/ZephyrTransport/zephyr-website/blob/gh-pages/_projects/4-open-science.md

**Comment by e-lo** [comment]
I just made you an owner @lmz  so you should be able to add anyone, although it doesn't look like that is a valid GH handle...

**Comment by jfhawkin** [comment]
I've updated the page. I'll review it with the group at our next Open Science meeting and make additional changes.
