### ISSUE TITLE
Membership Page

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/zephyr-website#9]

**Comment by e-lo** [comment]
Going to refine based on txt from google doc...

**Comment by e-lo** [comment]
Thinking this thru a little bit more - i'm wondering if we want to change the wording of "corporations" to "institutions" in order to include universities??  hmm

**Comment by billyc** [comment]
@e-lo  I added wording to cover corporate and institutions.  But basically it says "contact us" -- I didn't list the corporate/institutional rates.  Let me know if we should add that to the page. (Or feel free to edit)
